name: Build image and pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get RAIMAD
        run: ./scripts/gh-actions/get-raimad.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "Dockerfile"
          tags: raidoc:latest
          load: true
          push: true
          # This caches docker layers to github actions cache
          cache-from: type=gha
          # chaching is completely broken for max mode
          # idk why
          cache-to: type=gha,mode=min

      - name: Build raidoc
        uses: addnab/docker-run-action@v3
        with:
          image: raidoc:latest
          run: /venv/bin/python -m raidoc build
          options: |
            -v ${{ github.workspace }}/raimad-symlink:/venv/lib/python3.14/site-packages/raimad
            -v .:/pwd
            --workdir /pwd

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  pages:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

