name: Build image and pages

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: "Cachedance: dockerfile"
        uses: actions/cache@v4
        id: cache
        with:
          path: cache-mount
          key: cache-mount-${{ hashFiles('Dockerfile') }}

      - name: "Cachedance: restore cache mounts"
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-dir: cache-mount
          dockerfile: Dockerfile
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Docker build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "Dockerfile"
          tags: ghcr.io/${{ github.repository }}/raidoc:latest
          load: true
          push: true
          # This caches docker layers to github actions cache
          cache-from: type=gha
          # chaching is completely broken for max mode
          # idk why
          cache-to: type=gha,mode=min

      - name: Attemp restore raidoc dep cache
        id: cache-raidoc-restore
        uses: actions/cache/restore@v6
        with:
          path: |
            /var/cache/raidoc-dep
          key: ${{ runner.os }}-raidoc-dep

      - name: Build raidoc
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/${{ github.repository }}/raidoc:latest
          run: |
            set -e
            . /venv/bin/activate
            pip install -r ./raimad.requirement.txt
            python -m raidoc build --cache /var/cache/raidoc-dep
            ./scripts/gh-actions/make-release-tarball.sh
          options: |
            -v ${{ github.workspace }}/raimad-symlink:/venv/lib/python3.14/site-packages/raimad
            -v ${{ github.workspace }}:/pwd
            --workdir /pwd

      - name: Save raidoc dep cache
        id: cache-raidoc-save
        uses: actions/cache/save@v6
        with:
          path: |
            /var/cache/raidoc-dep
          key: ${{ steps.cache-raidoc-restore.outputs.cache-primary-key }}

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

      - name: Upload release artifact
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.zst"

  pages:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

